# output "vaultvm_ip" {
#   description = "Vault VM IP"
#   value       = module.vaultvm.vaultvm_ip
# }

# output "vaultvm_username" {
#   description = "Vault VM username"
#   value       = module.vaultvm.vaultvm_username
# }

# output "vaultvm_password" {
#   description = "Vault VM admin password"
#   value       = module.vaultvm.vaultvm_password
#   sensitive   = true
# }


output "ssh_private_key" {
  sensitive = true
  value     = tls_private_key.aks_key.private_key_pem
}

output "kube_admin_config" {
  description = "Admin KubeConfig file"
  sensitive   = true
  value       = module.aks.kube_admin_config
}

output "cluster_name" {
  description = "Autogenerated cluster name"
  value       = module.aks.cluster_name
}

output "host" {
  value     = module.aks.host
  sensitive = true
}

output "kube_admin_client_certificate" {
  sensitive = true
  value     = module.aks.kube_admin_client_certificate
}

output "kube_admin_client_key" {
  value     = module.aks.kube_admin_client_key
  sensitive = true
}

output "cluster_ca_certificate" {
  value     = module.aks.cluster_ca_certificate
  sensitive = true
}
